GET http://localhost:3000/multiple
###

GET http://localhost:3000/data/Monday
###
POST http://localhost:3000/post
Content-Type: application/json

{
    "value": "TEST",
    "weekday": "Tuesday"
}

###
DELETE http://localhost:3000/delete/zJQas4Bd9xJNDy5UvzE2N